swagger: "2.0"
info:
  version: "0.0.1"
  title: Fetch API
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
tags:
- name: "admins"
  description: "Secured Admin-only calls"
- name: "developers"
  description: "Operations available to regular developers"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user:
    x-swagger-router-controller: users
    get:
      tags:
      - "admins"
      summary: "Gets list of users"
      operationId: "listUsers"
      produces:
      - "application/json"
      responses:
        "200":
          description: Sucess
          schema:
            $ref: "#/definitions/GetUserListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
      - "admins"
      summary: "Add user to database"
      operationId: "createUser"
      parameters:
        - name: user
          in: body
          required: true
          description: New User details to add
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successfully added user"
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello: 
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  GetUserListResponse:
    required:
      - users
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/User"
  User:
    required:
      - name
      - email
    properties:
      name:
        type: string
        description: User name
      email:
        type: string
        description: User email
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  
      